name: Build and Restore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Restore NuGet packages
      run: msbuild "C:\Users\redpe\source\repos\Gorev\Gorev.sln" /t:Restore /p:Configuration=Debug

    - name: Build
      run: msbuild "C:\Users\redpe\source\repos\Gorev\Gorev.sln" /p:Configuration=Debug
